version: 0.0
Resources:
  - TargetService:
      Type: AWS::Lambda::Function
      Properties:
        Name: JavaAPI
        Alias: CodeDeployVersion
        CurrentVersion: 1  # Ensure a valid version number is specified
        TargetVersion: 1