version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - chmod +x gradlew  # Add this line to make the gradlew script executable
  build:
    run-as: root
    commands:
      # Ensure we are in the correct directory (root directory) and perform a gradle build.
      # This will create the Lambda.zip file in the build/distributions directory.
      # Copy that zip file into the root directory.
      - echo "Starting build..."
      - echo Build started on `date`
      - cd ${CODEBUILD_SRC_DIR}
      - echo "Running ls"
      - ls
      - ./gradlew clean build
      - cp build/distributions/*.zip Lambda.zip


  post_build:
    commands:
      - echo Build completed on `date`

# Reference the Lambda.zip file that we copied into the root directory.
# This artifact will be uploaded into S3. 
artifacts:
  files:
    - Lambda.zip
    - appspec.yaml