version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - chmod +x gradlew  # Add this line to make the gradlew script executable
  build:
    run-as: root
    commands:
      # Build checkHyperScience function
      - echo "Starting build..."
      - echo Build started on `date`
      - cd ${CODEBUILD_SRC_DIR}
      - echo "Running ls"
      - ls
      - ../gradlew clean build

  post_build:
    commands:
      - echo Build completed on `date`
      - zip -r Lambda.zip build/*  # Package the build artifacts into a zip file

artifacts:
  files:
    - Lambda.zip